//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POS_WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כתובת.
        /// </summary>
        public static string ADDRESS {
            get {
                return ResourceManager.GetString("ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סכום.
        /// </summary>
        public static string AMOUNT {
            get {
                return ResourceManager.GetString("AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ברקוד.
        /// </summary>
        public static string BARCODE {
            get {
                return ResourceManager.GetString("BARCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחיר עלות.
        /// </summary>
        public static string BAYPRICE {
            get {
                return ResourceManager.GetString("BAYPRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יום הולדת.
        /// </summary>
        public static string BIRTHDAY {
            get {
                return ResourceManager.GetString("BIRTHDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מותג.
        /// </summary>
        public static string BRAND {
            get {
                return ResourceManager.GetString("BRAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בטל.
        /// </summary>
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עיר.
        /// </summary>
        public static string CITY {
            get {
                return ResourceManager.GetString("CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם החברה.
        /// </summary>
        public static string COMPONYNAME {
            get {
                return ResourceManager.GetString("COMPONYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to איש קשר.
        /// </summary>
        public static string CONTACT {
            get {
                return ResourceManager.GetString("CONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אנשי קשר.
        /// </summary>
        public static string CONTACTS {
            get {
                return ResourceManager.GetString("CONTACTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לקוחות.
        /// </summary>
        public static string CUSTOMERS {
            get {
                return ResourceManager.GetString("CUSTOMERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחק.
        /// </summary>
        public static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחלקה.
        /// </summary>
        public static string DEPARTMENT {
            get {
                return ResourceManager.GetString("DEPARTMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחלקות.
        /// </summary>
        public static string DEPARTMENTS {
            get {
                return ResourceManager.GetString("DEPARTMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחלקות וקבוצות.
        /// </summary>
        public static string DEPARTMENTS_AND_GROUPS {
            get {
                return ResourceManager.GetString("DEPARTMENTS_AND_GROUPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאור.
        /// </summary>
        public static string DESCRIPTION {
            get {
                return ResourceManager.GetString("DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ערוך.
        /// </summary>
        public static string EDIT {
            get {
                return ResourceManager.GetString("EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to דוא&quot;ל.
        /// </summary>
        public static string EMAIL {
            get {
                return ResourceManager.GetString("EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קוד עובד.
        /// </summary>
        public static string EMPID {
            get {
                return ResourceManager.GetString("EMPID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עובדים.
        /// </summary>
        public static string EMPLOYEES {
            get {
                return ResourceManager.GetString("EMPLOYEES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאריך סיום.
        /// </summary>
        public static string ENDDATE {
            get {
                return ResourceManager.GetString("ENDDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם פרטי.
        /// </summary>
        public static string FIRSTNAME {
            get {
                return ResourceManager.GetString("FIRSTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קבוצה.
        /// </summary>
        public static string GROUP {
            get {
                return ResourceManager.GetString("GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קבוצות.
        /// </summary>
        public static string GROUPS {
            get {
                return ResourceManager.GetString("GROUPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1280.
        /// </summary>
        public static string H {
            get {
                return ResourceManager.GetString("H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר בית.
        /// </summary>
        public static string HOUSENUM {
            get {
                return ResourceManager.GetString("HOUSENUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קוד.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם משפחה.
        /// </summary>
        public static string LASTNAME {
            get {
                return ResourceManager.GetString("LASTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאריך עדכון.
        /// </summary>
        public static string LASTUPDATEDATE {
            get {
                return ResourceManager.GetString("LASTUPDATEDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תפריט.
        /// </summary>
        public static string MENU {
            get {
                return ResourceManager.GetString("MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם התפריט.
        /// </summary>
        public static string MENUNAME {
            get {
                return ResourceManager.GetString("MENUNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תפריטים.
        /// </summary>
        public static string MENUS {
            get {
                return ResourceManager.GetString("MENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חדש.
        /// </summary>
        public static string NEW {
            get {
                return ResourceManager.GetString("NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סיסמא.
        /// </summary>
        public static string PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הרשאות.
        /// </summary>
        public static string PERMISSIONS {
            get {
                return ResourceManager.GetString("PERMISSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר טלפון.
        /// </summary>
        public static string PHONENUM {
            get {
                return ResourceManager.GetString("PHONENUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פרטים אישיים.
        /// </summary>
        public static string PORSONDETAIL {
            get {
                return ResourceManager.GetString("PORSONDETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם המוצר.
        /// </summary>
        public static string PRODUCTNAME {
            get {
                return ResourceManager.GetString("PRODUCTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מוצרים.
        /// </summary>
        public static string PRODUCTS {
            get {
                return ResourceManager.GetString("PRODUCTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תפקיד.
        /// </summary>
        public static string ROLE {
            get {
                return ResourceManager.GetString("ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחיר מחירון.
        /// </summary>
        public static string SALEPRICE {
            get {
                return ResourceManager.GetString("SALEPRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שכר.
        /// </summary>
        public static string SALERY {
            get {
                return ResourceManager.GetString("SALERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סוג שכר.
        /// </summary>
        public static string SALRYTYPE {
            get {
                return ResourceManager.GetString("SALRYTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שמור.
        /// </summary>
        public static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SaveDeniedContent {
            get {
                return ResourceManager.GetString("SaveDeniedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא ניתן לבצע שמירה.
        /// </summary>
        public static string SaveDeniedTitle {
            get {
                return ResourceManager.GetString("SaveDeniedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאריך התחלה.
        /// </summary>
        public static string STARTDATE {
            get {
                return ResourceManager.GetString("STARTDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רחוב.
        /// </summary>
        public static string STREET {
            get {
                return ResourceManager.GetString("STREET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר רחוב.
        /// </summary>
        public static string STREETNUM {
            get {
                return ResourceManager.GetString("STREETNUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ספק.
        /// </summary>
        public static string VANDOR {
            get {
                return ResourceManager.GetString("VANDOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ספקים.
        /// </summary>
        public static string VENDORS {
            get {
                return ResourceManager.GetString("VENDORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1024.
        /// </summary>
        public static string W {
            get {
                return ResourceManager.GetString("W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מיקוד.
        /// </summary>
        public static string ZIPCODE {
            get {
                return ResourceManager.GetString("ZIPCODE", resourceCulture);
            }
        }
    }
}
