//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSEntities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditPaymentsDetail
    {
        public int ID { get; set; }
        public int CreditPaymentID { get; set; }
        public int PaymentNumber { get; set; }
        public decimal Amount { get; set; }
    
        public virtual CreditPayment CreditPayment { get; set; }
    }
}
