//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSEntities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyAttendance
    {
        public int empId { get; set; }
        public System.DateTime entryTime { get; set; }
        public Nullable<System.DateTime> exitTime { get; set; }
        public bool isPresent { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
