//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSEntities.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Department : ModelBase,IUnDeleteableEntity
    {
        public Department()
        {
            this.Groups = new HashSet<Group>();
            this.Products = new HashSet<Product>();
        }
    
        public int ID { get; set; }
        [Required(ErrorMessage="שם מחלקה הוא שדה חובה")]
        public string DeptName { get { return GetValue(() => DeptName).Trim(); } set { SetValue(() => DeptName, value.Trim()); } }
        public bool Mode { get; set; }
    
        public virtual ICollection<Group> Groups { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
