//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSEntities.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class EmployeeSalery: ModelBase
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public int SaleryTypeID { get; set; }
        [Required(ErrorMessage="סכום הוא שדה חובה")]
        [Range(1,99999,ErrorMessage="סכום יכול להיות בין 1 ל 99999 שח")]
        public decimal Amount { get { return GetValue(() => Amount); } set { SetValue(() => Amount, value); } }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual SaleryType SaleryType { get; set; }
    }
}
