//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSEntities.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Employee : Person
    {
        public Employee()
        {
            this.DailyAttendances = new HashSet<DailyAttendance>();
            this.EmployeeSaleries = new HashSet<EmployeeSalery>();
            this.Orders = new HashSet<Order>();
            this.ZReports = new HashSet<ZReport>();
        }
        [Required]
        [Range(1,9999,ErrorMessage="חובה לבחור תפקיד")]
        public int RoleID { get { return GetValue(() => RoleID); } set { SetValue(() => RoleID, value); } }
    
        public virtual ICollection<DailyAttendance> DailyAttendances { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<EmployeeSalery> EmployeeSaleries { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<ZReport> ZReports { get; set; }
        public override bool IsEmployee
        {
            get { return true; }
        }
    }
}
