//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSEntities.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Group : ModelBase, IUnDeleteableEntity
    {
        public Group()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int ID { get; set; }
        [Required(ErrorMessage="שם קבוצה הוא שדה חובה")]
        public string GroupName { get { return GetValue(() => GroupName); } set { SetValue(() => GroupName, value); } }
        [Range(1,9999,ErrorMessage="חובה לבחור קבוצה")]
        public int DepartmentID { get { return GetValue(() => DepartmentID); } set { SetValue(() => DepartmentID, value); } }
        public bool Mode { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
