//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSEntities.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Menu : ModelBase, IDisplayableModel
    {
        public Menu()
        {
            this.ContainItemDisplayInfoes = new HashSet<ItemDisplayInfo>();
            this.ItemDisplayInfoes = new HashSet<ItemDisplayInfo>();
        }
    
        public int ID { get; set; }
        [Required(ErrorMessage="שם התפריט הוא שדה חובה")]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "שם התפריט חייב להיות בין 2 ל 50 תוים")]
        public string Name { get { return GetValue(() => Name); } set { SetValue(() => Name, value); } }
    
        public virtual ICollection<ItemDisplayInfo> ContainItemDisplayInfoes { get; set; }
        public virtual ICollection<ItemDisplayInfo> ItemDisplayInfoes { get; set; }

        public ItemDisplayInfo GetNewDiplayInfo()
        {
            ItemDisplayInfo item = new ItemDisplayInfo()
            {
                DisplayName = this.Name,
                IsMenu = true,
                ItemID = this.ID
            };
            this.ItemDisplayInfoes.Add(item);
            return item;
        }
    }
}
