//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSEntities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment : ModelBase
    {
        public int ID { get; set; }
        public decimal TotalPayed { get { return GetValue(() => TotalPayed); } set { SetValue(() => TotalPayed, value); } }
        public int OrderID { get; set; }
        public string PaymentTypeName { get { return GetValue(() => PaymentTypeName).Trim(); } set { SetValue(() => PaymentTypeName, value); } }
    
        public virtual Order Order { get; set; }
    }
}
