//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSEntities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonType
    {
        public PersonType()
        {
            this.People = new HashSet<Person>();
        }
    
        public int personTypeId { get; set; }
        public string personTypeName { get; set; }
    
        public virtual ICollection<Person> People { get; set; }
    }
}
