//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSEntities.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Person : ModelBase, IUnDeleteableEntity
    {

        public int ID { get; set; }
        [Required(ErrorMessage="שם פרטי הוא שדה חובה")]
        public string FirstName { get { return GetValue(() => FirstName); } set { SetValue(() => FirstName, value); FullName = FirstName + " " + LastName; } }
        [Required(ErrorMessage="שם משפחה הוא שדה חובה")]
        public string LastName { get { return GetValue(() => LastName); } set { SetValue(() => LastName, value); FullName = FirstName + " " + LastName; } }
        public string FullName { get { return GetValue(() => FullName); } set { SetValue(() => FullName, value); } }
        public Nullable<System.DateTime> Birthday { get; set; }
        [Phone]
        public string PhoneNum { get { return GetValue(() => PhoneNum); } set { SetValue(() => PhoneNum, value); } }
        [EmailAddress(ErrorMessage="כתובת המייל אינה תקינה")]
        public string Email { get { return GetValue(() => Email); } set { SetValue(() => Email, value); } }
        public Nullable<int> AddressID { get; set; }
        public bool Mode { get; set; }
        [Required(ErrorMessage="סיסמא הוא שדה חובה")]
        [StringLength(20,MinimumLength=4,ErrorMessage="סיסמא חייבת להיות בין 4 ל 20 תוים")]
        public string Password { get { return GetValue(() => Password); } set { SetValue(() => Password, value); } }
        public Nullable<int> PersonTypeID { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual PersonType PersonType { get; set; }

        public virtual bool IsCustomer { get { return false; } }
        public virtual bool IsEmployee { get { return false; } }
        public virtual bool IsContact { get { return false; } }
    }
}
