//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSEntities.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Product : ModelBase,IUnDeleteableEntity, IDisplayableModel
    {
        public Product()
        {
            this.ItemDisplayInfoes = new HashSet<ItemDisplayInfo>();
            this.OrderLines = new HashSet<OrderLine>();
        }

        public int ID { get; set; }

        [Required(ErrorMessage="שם המוצר הוא שדה חובה")]
        [StringLength(50,MinimumLength=2,ErrorMessage="שם המוצר יכול להכיל בין 2 ל 50 תווים")]
        public string prodName { get { return GetValue(() => prodName); } set { SetValue(() => prodName, value); } }

        [Required]
        [Range(1,9999,ErrorMessage="חובה לבחור מחלקה")]
        public int deptId { get { return GetValue(() => deptId); } set { SetValue(() => deptId, value); } }

        [Required]
        [Range(1,9999,ErrorMessage="חובה לבחור קבוצה")]
        public int groupId { get { return GetValue(() => groupId); } set { SetValue(() => groupId, value); } }

        [Display(AutoGenerateField=false)]
        public Nullable<int> VandorID { get; set; }

        [Required]
        [Range(0.1,99999,ErrorMessage="מחיר יכול להיות בין 0.1 ל 99999 שח")]
        public decimal salePrice { get { return Math.Round(GetValue(() => salePrice),2); } set { SetValue(() => salePrice, value); } }
        public Nullable<decimal> bayPrice { get; set; }
        public string bacode { get; set; }
        public string brand { get; set; }
        public Nullable<System.DateTime> lastUpdateDate { get; set; }

        public bool mode { get; set; }
        public string description { get; set; }
    
        public virtual Department Department { get; set; }

        public virtual Group Group { get; set; }
        public virtual ICollection<ItemDisplayInfo> ItemDisplayInfoes { get; set; }
        public virtual ICollection<OrderLine> OrderLines { get; set; }

        public virtual Vendor Vendor { get; set; }


        public ItemDisplayInfo GetNewDiplayInfo()
        {
            ItemDisplayInfo item = new ItemDisplayInfo()
            {
                DisplayName = this.prodName,
                ItemID = this.ID
            };
            this.ItemDisplayInfoes.Add(item);
            return item;
        
        }

        public bool Mode
        {
            get
            {
                return this.mode;
            }
            set
            {
                this.mode = value;
            }
        }
    }
}
