//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSEntities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleryType
    {
        public SaleryType()
        {
            this.EmployeeSaleries = new HashSet<EmployeeSalery>();
        }
    
        public int SaleryTypeID { get; set; }
        public string SaleryTypeName { get; set; }
    
        public virtual ICollection<EmployeeSalery> EmployeeSaleries { get; set; }
    }
}
