//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSEntities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreInfo
    {
        public StoreInfo()
        {
            this.Cashiers = new HashSet<Cashier>();
            this.Orders = new HashSet<Order>();
        }
    
        public int StoreID { get; set; }
        public string Name { get; set; }
        public Nullable<int> AddressID { get; set; }
        public string BranchName { get; set; }
    
        public virtual ICollection<Cashier> Cashiers { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
