//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSEntities.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Vendor : ModelBase, IUnDeleteableEntity
    {
        public Vendor()
        {
            this.Products = new HashSet<Product>();
            this.Contacts = new HashSet<Contact>();
        }
    
        public int ID { get; set; }
        [Required(ErrorMessage="שם החברה הוא שדה חובה")]
        public string CompanyName { get { return GetValue(() => CompanyName); } set { SetValue(() => CompanyName, value); } }
        public Nullable<int> AddressID { get; set; }

        public bool Mode { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<Contact> Contacts { get { return GetValue(() => Contacts); } set { SetValue(() => Contacts, value); } }
    }
}
