//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSEntities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZReport
    {
        public ZReport()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int ZNumber { get; set; }
        public int empId { get; set; }
        public System.DateTime reportDate { get; set; }
        public decimal reprotTotalAmount { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
