//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuDesign.Models
{
    using Prism.Mvvm;
    using System;
    using System.Collections.Generic;
    
    public partial class MenuSetView : BindableBase
    {
        public int itemid { get; set; }
        public int id { get; set; }
        public int locationX { get; set; }
        public int locationY { get; set; }
        public int indexRow { get; set; }
        public int indexCell { get; set; }
        public int numOfRows { get; set; }
        public int numOfCells { get; set; }
        public string type { get; set; }
        public Nullable<int> color { get; set; }
        public string image { get; set; }
        public Nullable<int> foreColor { get; set; }
        public string fontString { get; set; }
        public string Name { get { return _name; } set { SetProperty(ref _name, value); } }
        private string _name;
    }
}
